<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../ParcelBox.Application/ParcelBox.Application.csproj" />
    <ProjectReference Include="../ParcelBox.Infrastructure/ParcelBox.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
</Project>
